import next from "@next/eslint-plugin-next";
import smolpack from "@smolpack/eslint-config";

export default [
	...smolpack,
	next.configs["core-web-vitals"],
	{
		files: ["scripts/**/*.mjs"],
		languageOptions: {
			globals: {
				process: "readonly",
				console: "readonly",
				Buffer: "readonly",
				fetch: "readonly",
			},
		},
	},
	{
		ignores: [
			".next/**",
			"node_modules/**",
			"app/schemas/sharepoint-v2/*.json",
		],
	},
	{
		settings: {
			"import/resolver": {
				typescript: {
					project: "./tsconfig.json",
				},
			},
		},
	},
	{
		files: ["next-env.d.ts"],
		rules: {
			// `.next/types/routes.d.ts` is generated by Next.js at build/dev time.
			// Keep the import, but avoid failing lint in clean checkouts/CI.
			"import/no-unresolved": "off",
		},
	},
];
